### ISSUE TITLE
Linker errors against engine libraries when building "AtomSampleViewerStandalone" project

### ISSUE THREAD

**Issue by Impulse21** [o3de/o3de-atom-sampleviewer#168]
Steps:
Followed steps from [.](https://o3de.org/docs/atom-guide/setup-atom-projects/)

When building the project, 3 projects fail due to linker errors.

Example of build output:

```
6>------ Build started: Project: AtomSampleViewerStandalone, Configuration: debug x64 ------
6>Vcpkg is unable to link because we cannot decide between Release and Debug libraries. Please define the property VcpkgConfiguration to be 'Release' or 'Debug' (currently 'debug').
6>LINK : fatal error LNK1104: cannot open file '$<$<CONFIG:profile>:D:\Users\<Folder>\o3de\install\lib\Windows\profile\AtomCore.lib>'
```

Seems the path is in correct. Not sure where the "$<$<CONFIG:profile>: " bit comes from.

NOTE: I have ensured that the asset processor was not running when trying to build this solution.

**Comment by superkitcath** [comment]
@Impulse21 ; is this still happening? Thanks!

**Comment by Impulse21** [comment]
Hi, it's been a while. I will try to repo this week and let you know.

**Comment by Impulse21** [comment]
I am going to close this out. As I don't know when I will be able to get around seeing if I can still repo.
