### ISSUE TITLE
New labels needed

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de-atom-sampleviewer#354]
Hi! 

We would need the priority labels, as well as needs-triage and needs-information labels on this repo. 

Thanks!

**Comment by forhalle** [comment]
I unfortunately do not have rights in this repo to add labels. Please talk to the sig lead.

**Comment by superkitcath** [comment]
@amzn-changml, as discussed, those are the labels I need to create :-)

**Comment by amzn-changml** [comment]
I've granted write access to the Project-Mainainers team, which you are a member of. Can you verify?

**Comment by superkitcath** [comment]
> I've granted write access to the Project-Mainainers team, which you are a member of. Can you verify?

It works! Thanks!

**Comment by superkitcath** [comment]
The following labels were created: needs-triage, priority/blocker, priority/critical, priority/major, priority/minor.
