### ISSUE TITLE
ASV Vulkan Full Test Suite Crashes Device Lost

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de-atom-sampleviewer#359]
[Migrated from JIRA ATOM-17400]
When I run ASV full test suite on vulkan it almost always crashes with "Device Lost" during the "FastCheckSample" stages. It seems like this crash does _not_ happen when the cache was deleted and freshly built. But then any subsequent runs will crash. But I'm not sure this is true 100%.
----
Found in Build:

Reproducibility:

Prerequisites:

Steps to Reproduce:

Run ASV full test suite on vulkan.

Expected Result:

Complete all test cases.

Actual Result:

Device Lost and crash.

**Comment by VickyAtAZ** [comment]
I couldn't repro the device lost crash with stabilization 2205 branch commit 651a5a380b02e8244011cb3d2458787a083e4e74. I have tried to run the full test suite 3 times and it didn't happen.
Although I found test failure with RenderTargetTexture sample test when run the full test suite the second time. Here is the fix
https://github.com/o3de/o3de/pull/9062
