### ISSUE TITLE
ASV: Parallax Feature sample crashes on load

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de-atom-sampleviewer#370]
[Migrated from JIRA ATOM-17450]
ASV: Parallax Feature sample crashes on load
----
O3de:
commit a78dcd3177ec441dc1d3329fb2fe71e9b0c4f0f1

ASV:
commit 6037b516478322d5f3e288d191ceee62b01f17ce

Reproducibility:
100%

Prerequisites:
Build the above commits and process all assets

Steps to Reproduce:
1. Launch AtomSampleViewerStandalone.exe
2. Go to: Samples > Features > Parallax
3. Observe sample

Expected Result:
 - Sample loads

Actual Result:
 - ASV crashes (see attached logs)

**Comment by LB-TomaszSerwanski** [comment]
The issue still occurs both in the following Stabilization and development branches:
ASV: Stabilization/2205([3efc7e3](https://github.com/o3de/o3de-atom-sampleviewer/commit/3efc7e3ae3d7441257ab3e68ccc457ff6b0f8491))
ASV: Development ([3efc7e3](https://github.com/o3de/o3de-atom-sampleviewer/commit/3efc7e3ae3d7441257ab3e68ccc457ff6b0f8491))

O3DE: O3DE: Stabilization/2205:Installer
O3DE: Development (8712cc3)

In addition to the crash, there are two Asserts

![image](https://user-images.githubusercontent.com/86953108/162413927-a4a18cd6-39c2-4b7b-bb16-1b71cb9f42f6.png)

![image](https://user-images.githubusercontent.com/86953108/162413986-1045a809-974f-43c3-bf54-ace6bfc4a0e8.png)

See the logs attached in [log.zip](https://github.com/o3de/o3de-atom-sampleviewer/files/8450849/log.zip).

Please reopen the issue or let us know if it should be reported as a new ticket.

**Comment by LB-JaroslawGaweda** [comment]
We encountered this issue on Development O3DE: (a16d07a) and ASV: Development (https://github.com/o3de/o3de-atom-sampleviewer/commit/9db53011ea6c70f9d6eb75edc4f15113f36351b1). With exactly the same errors as the ones in @LB-TomaszSerwanski comment.
