### ISSUE TITLE
ASV: RPI ShaderReloadTest only loads a flat red screen, no menu options present

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de-atom-sampleviewer#374]
[Migrated from JIRA ATOM-17448]
ASV: RPI ShaderReloadTest only loads a flat red screen, no menu options present
----
Found in Build:

O3de:
commit a78dcd3177ec441dc1d3329fb2fe71e9b0c4f0f1

ASV:
commit 6037b516478322d5f3e288d191ceee62b01f17ce

Reproducibility:
100%

Prerequisites:
 - Build the above commits and process all assets

Steps to Reproduce:
1. Launch AtomSampleViewerStandalone.exe
2. Go to: Samples > RPI > ShaderReloadTest
3. Observe sample

Expected Result:
 - Sample loads with menu options

Actual Result:
 - Sample loads to a flat red screen with no menus

**Comment by santorac** [comment]
Assigned to @antonmic because he has a fix here: https://github.com/o3de/o3de-atom-sampleviewer/pull/482

**Comment by moudgils** [comment]
Old bug. closing it. Will open a new issue if needed
