### ISSUE TITLE
ASV: "Shadow" Feature sample hangs then causes AtomSampleViewer to crash when user cancels "Waiting for assets..." dialog

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de-atom-sampleviewer#375]
[Migrated from JIRA ATOM-17452]
ASV: RPI Multiscene sample crashes on load

O3de:
commit a78dcd3177ec441dc1d3329fb2fe71e9b0c4f0f1

ASV:
commit 6037b516478322d5f3e288d191ceee62b01f17ce

Reproducibility:
100%

Prerequisites:
 - Build the above commits and process all assets

Steps to Reproduce:
1. Launch AtomSampleViewerStandalone.exe
2. Go to: Samples > Features >Shadow
3. Wait for asset to finish processing
4. Select "Cancel" on the "Waiting for assets..." dialog

Expected Result:
 - Sample loads

Actual Result:
 - Sample never loads and hangs indefinitely until canceled (see attached)

**Comment by NeilGitGud** [comment]
[Shadow_sample_AtomSampleViewer.log](https://github.com/o3de/o3de-atom-sampleviewer/files/8268325/Shadow_sample_AtomSampleViewer.log)

**Comment by superkitcath** [comment]
Sending back to triage, as it needs a new assignee

**Comment by moudgils** [comment]
Old bug. Closing it. Will open a new one with latest info if needed.
