### ISSUE TITLE
[Linux] AtomTest fails to build via CLI and Ubuntu freezes after attempting to build it via Project Manager

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de-atom-sampleviewer#397]
**Describe the bug**
System freezes after a few minutes of building AtomTest project via the Project Manager. A hardware reset is required for the system to recover. When attempting to build the project using CLI, building fails and a "ninja: build stopped: subcommand failed" error is displayed.

**Steps to reproduce**
1. Clone the project using the following commands:
          git clone https://github.com/o3de/o3de-atomtest.git
          git pull Stabilization/2205
2. Launch the Project Manager, press New Project> Add Existing Project.
3. Select the AtomTest project and add it to the Project Manager.
4. Press Build Project> Build Now.

Steps to build via the CLI:
1. Clone the project using the following commands:
          git clone https://github.com/o3de/o3de-atomtest.git
          git pull Stabilization/2205
2. Move to the AtomTest folder and build the project using following commands:
          cmake -B build/linux -S . -G "Ninja Multi-Config" -DLY_3RDPARTY_PATH=$HOME/o3de-packages
          cmake --build build/linux --target Editor AtomTest.GameLauncher --config profile -j 8

**Expected behavior**
The project build successfully. The system is responsive.

**Actual behavior**
The project fails to build via the CLI. The system freezes after a few of minutes of building via the Project Manager.

**Found in Branch**
Stabilization_2205 ([3e47df2](https://github.com/o3de/o3de-atom-sampleviewer/commit/3efc7e3ae3d7441257ab3e68ccc457ff6b0f8491))

Desktop
• Device: PC
• OS: Ubuntu
• Version: Ubuntu 20.04.4 LTS
• CPU Intel Core i7-9700K
• GPU Nvidia GeForce RTX 2070
• Memory 16GB

**Comment by smurly** [comment]
AtomTest project is in deprecation and has not been maintained. AutomatedTesting is replacing the AtomTest project.
