### ISSUE TITLE
AtomSampleViewer project fails to configure through the terminal when no engine named "o3de" is registered

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de-atom-sampleviewer#400]
**Describe the bug**
AtomSampleViewer project cannot be configured using the terminal when no "o3de" engine is registered. This causes issues when using the o3de installer, as it registers the engine as "o3de-sdk" (or registering the engine with another name).

The workaround is to configure and build ASV using the Installer's Project Manager.

Please note that the issue occurs both in Windows and Linux.

Please refer to the attached files for more details.

**Prerequisite**
- O3DE installed from the Stabilization/2205 installer.
- No other O3DE engines registered.

**Steps to reproduce**
1. Clone the AtomSampleViewer repository.
2. Attempt to generate the Cmake project by executing the following command in the CLI: 
`cmake -B "C:\AtomSampleViewer\build" -S "C:\AtomSampleViewer" -G "Visual Studio 16" -DLY_3RDPARTY_PATH=C:\o3de-packages`

**Expected behavior**
The CMake project is generated successfully.

**Actual behavior**
The CMake project fails to generated due to missing "o3de" engine.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/86953108/162434723-ff558982-b0dd-4e02-b9c1-f6b05a241e56.png)

![image](https://user-images.githubusercontent.com/86953108/162435245-76e4ad89-24f1-4866-8cdc-db6f2e685818.png)

**Found in Branch**
ASV: Stabilization/2205([3efc7e3](https://github.com/o3de/o3de-atom-sampleviewer/commit/3efc7e3ae3d7441257ab3e68ccc457ff6b0f8491))
O3DE: Stabilization/2205:Installer

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by moudgils** [comment]
Old issue. Check if this is still applicable and close if not.

**Comment by LB-TomaszSerwanski** [comment]
Closing the issue as it no longer occurs on the latest Development and Stabilization/2305 branches.
