### ISSUE TITLE
testdata/objects/cube/cube.azmodel cannot be processed when using the O3DE installer

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de-atom-sampleviewer#401]
**Describe the bug**
If the AtomSampleViewer project was set up using the o3de installer, the testdata/objects/cube/cube.azmodel does not finish processing. This prevents multiple samples to be loaded (i.e. RPI/MultiRenderPipeline, RPI/MultiScene).

Please note, that AssetProcessor is idle while the _Waiting For Asset..._ window is displayed in the AtomSampleViewerStandalone.

The issue does not occur when the ASV was built from the source engine O3DE.

Please refer to the attached video for more details.

**Prerequisite**
- AtomSampleViewer set up using the Stabilization/2205 O3DE installer 

**Steps to reproduce**
1. Launch AtomSampleViewerStandalone.exe.
2. Load Samples/RPI/MultiScene.

**Expected behavior**
The sample loads succesfully.

**Actual behavior**
The sample does not load as the cube.azmodel asset did not finish processing.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/162443178-fc481621-339b-45be-b4ae-116deff18ed6.mp4

**Found in Branch**
ASV: Stabilization/2205([3efc7e3](https://github.com/o3de/o3de-atom-sampleviewer/commit/3efc7e3ae3d7441257ab3e68ccc457ff6b0f8491))
O3DE: Stabilization/2205:Installer

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by moudgils** [comment]
Old issue. Check if this is still happening. I was unable to repro it. Close if not applicable.

**Comment by LB-TomaszSerwanski** [comment]
Closing the issue as it no longer occurs on the latest Development and Stabilization/2305 branches.
