### ISSUE TITLE
Issues when loading RPI/AuxGeom sample

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de-atom-sampleviewer#402]
**Describe the bug**
The following issues occur when loading the RPI/AuxGeom sample on a specific platform:
- Windows:
Loading the RPI/AuxGeom sample takes over 15 minutes on a mid-range machine. During that time, the Standalone is frozen and unusable.

- Linux:
Loading the RPI/AuxGeom sample crashes the AtomSampleViewer.GameLauncher (we were unable to verify on the Standalone due to #392).

Please note that the logs are not generated for the Linux crash.

**Prerequisite**
- AtomSampleViewer built.

**Steps to reproduce**
1. Launch AtomSampleViewerStandalone.exe.
2. Load Samples/RPI/AuxGeom.

**Expected behavior**
The sample loads succesfully.

**Actual behavior**
**Windows:**
- The Standalone freezes for a very long time (over 15 minutes) before loading the sample.

**Linux:** 
- The GameLauncher crashes.

**Found in Branch**
ASV: Stabilization/2205([3efc7e3](https://github.com/o3de/o3de-atom-sampleviewer/commit/3efc7e3ae3d7441257ab3e68ccc457ff6b0f8491))
O3DE: Stabilization/2205:Installer

**Desktop/Device:**

**Windows:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Linux:** 
- Device: PC
- OS: Ubuntu
- Version 20.04
- CPU Intel Core i5-9600k
- GPU Nvidia GeForce RTX 2060
- Memory 16GB

**Comment by galibzon** [comment]
I'm getting the same bug using `stabilization/2205` on both o3de & ASV.

**Comment by VickyAtAZ** [comment]
PR: https://github.com/o3de/o3de/pull/9027

**Comment by LB-MateuszSzweda** [comment]
Verified as fixed on both PC and Linux on Stabilization_2205 (fa43be1). RPI/AuxGeom sample loads quickly on both platforms and remains stable.
