### ISSUE TITLE
RHI/AlphaToCoverage sample only renders a white screen

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de-atom-sampleviewer#405]
**Describe the bug**
The RHI/AlphaToCoverage sample does not render anything but a white box covering the entire Viewport.

Please note that the issue does not occur on Linux.

Please refer to the attached screenshots for more details.

**Prerequisite**
- O3DE installed from the Stabilization/2205 installer.

**Steps to reproduce**
1. Launch AtomSampleViewerStandalone.exe.
2. Load the RHI/AlphaToCoverage sample.

**Expected behavior**
The sample contents are rendered successfully.

**Actual behavior**
Only a white screen is rendered.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/162704224-1e58d036-932c-474b-9964-d276e347de3d.mp4

**Found in Branch**
ASV: Stabilization/2205([3efc7e3](https://github.com/o3de/o3de-atom-sampleviewer/commit/3efc7e3ae3d7441257ab3e68ccc457ff6b0f8491))
O3DE: Stabilization/2205:Installer

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by galibzon** [comment]
I validated with
O3DE: stabilization/2210 (8b0cdb5c575ff09959d2d062d43e26482ac5a1cb)
ASV: stabilization/2210 (6e9e09cabd0193b1dc69aa3ddefdc8a04dad7eca)

Linux & Windows.

**Comment by LB-TomaszSerwanski** [comment]
The issue verified as fixed both on Stabilization (O3DE: aae3858, ASV: 6e9e09c) and Development (O3DE: 0277349, ASV: cae2ff6) branches.
