### ISSUE TITLE
[Linux] Materials in RPI/DynamicMaterialTest sample are not rendered properly

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de-atom-sampleviewer#406]
**Describe the bug**
Material is not rendered correctly after changing it in the Debug Menu. After switching to Lua or C++ test material, the material assigned to the entity is rendered as a static gray and the dynamic modifications are not occurring like it was observed with the default material.

**Steps to reproduce**
1. Launch the AtomSampleViewer.GameLauncher.
2. Load the DynamicMaterialTest sample (Samples > RPI > DynamicMaterialTest).
3. Change the default material.

**Expected behavior**
The material is changed and rendered correctly. The dynamic material modifications work as expected.

**Actual behavior**
Both C++ and Lua test materials are not rendered properly.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/162730768-1dfceb0f-96c8-4225-bc0e-dd0b69de1b57.mp4

**Found in Branch**
Stabilization/2205 [(3e47df2)](https://github.com/o3de/o3de/commit/3e47df2e0fea9f57d207e6c739938bd1c4019c98)

**Desktop/Device:**
- Device: PC
- OS: Ubuntu
- Version 20.04
- CPU Intel Core i5-9600k
- GPU Nvidia GeForce RTX 2060
- Memory 16GB

**Comment by galibzon** [comment]
I validated with
O3DE: stabilization/2210 (8b0cdb5c575ff09959d2d062d43e26482ac5a1cb)
ASV: stabilization/2210 (https://github.com/o3de/o3de-atom-sampleviewer/commit/6e9e09cabd0193b1dc69aa3ddefdc8a04dad7eca)

Linux & Windows.

**Comment by LB-BartoszDudzinski** [comment]
Hi @galibzon! I am afraid that the issue still occurs on LINUX Development (1b7e57d) and Stabilization/2210 (840e1f4). Both C++ and Lua test materials are not rendered properly just like in the video. Please note that I am unable to reopen this issue.

**Comment by LB-BartoszDudzinski** [comment]
The issue still occurs on latest Development branch on Linux.
