### ISSUE TITLE
Launching AtomSampleViewerStandalone displays 3 warnings in the command line terminal

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de-atom-sampleviewer#407]
**Describe the bug**
The following warnings appear in the command line terminal after launching the AtomSampleViewerStandalone.exe:

```
Memory: Trace::Warning
 D:/workspace/o3de/Code/Framework/AzCore/AzCore/Memory/AllocationRecords.cpp(420): 'void __cdecl AZ::Debug::AllocationRecords::SetMode(enum AZ::Debug::AllocationRecords::Mode)'
Memory: Records recording was disabled and now it's enabled! You might get assert when you free memory, if a you have allocations which were not recorded!
Memory: ==================================================================
```

```
SettingsRegistryMergeUtils:
==================================================================
SettingsRegistryMergeUtils: Trace::Warning
 D:/workspace/o3de/Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp(686): 'bool __cdecl AZ::SettingsRegistryMergeUtils::MergeSettingsToRegistry_ConfigFile(class AZ::SettingsRegistryInterface &,class AZStd::basic_string_view<char,struct AZStd::char_traits<char> >,const struct AZ::SettingsRegistryMergeUtils::ConfigParserSettings &)'
SettingsRegistryMergeUtils: Unable to open file "D:\AtomSampleViewer\Cache\pc\user.cfg"
SettingsRegistryMergeUtils: ==================================================================
```

```
AssetProcessorConnection::ConnectThread:
==================================================================
AssetProcessorConnection::ConnectThread: Trace::Warning
 D:/workspace/o3de/Code/Framework/AzFramework/AzFramework/Network/AssetProcessorConnection.cpp(231): 'void __cdecl AzFramework::AssetSystem::AssetProcessorConnection::ConnectThread(void)'
AssetProcessorConnection::ConnectThread: Network connection attempt failure, Connect returned error AzSockError::eASE_ECONNREFUSED
AssetProcessorConnection::ConnectThread: ==================================================================
```

Please note that we were unable to verify the issue on Linux due to #392.

Please refer to the attached screenshots for more details.

**Prerequisite**
- O3DE installed from the Stabilization/2205 installer.

**Steps to reproduce**
1. Launch AtomSampleViewerStandalone.exe.
2. Switch focus to the CLI.

**Expected behavior**
There are no warnings in the CLI.

**Actual behavior**
Three warnings are displayed in the CLI.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/86953108/162745457-6defa9b5-384c-47b0-8d83-fac37522f457.png)

**Found in Branch**
ASV: Stabilization/2205([3efc7e3](https://github.com/o3de/o3de-atom-sampleviewer/commit/3efc7e3ae3d7441257ab3e68ccc457ff6b0f8491))
O3DE: Stabilization/2205:Installer

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by moudgils** [comment]
AtomSampleViewerStandalone was removed from ASV. Closing this bug. Open a new one if this bug is re-proable in ASV.gamelauncher
