### ISSUE TITLE
[Android] Asset Processor fails to process SubpassInputComposition.shader file for AtomSampleViewer project

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de-atom-sampleviewer#409]
**Describe the bug**
The following Shader Asset job fails processing for the .shader asset:
`SubpassInputComposition.shader`

Please refer to the attached .log files for more information.

**Prerequisites**

- AtomSampleViewer is built using **--target ALL_BUILD** for Windows.
- Android assets are enabled in _\o3de\Registry\AssetProcessorPlatformConfig.setreg_.

**Steps to reproduce**.
1. Launch the AssetProcessor.exe from the _/AtomSampleViewer/build/bin/profile/_ directory.
2. Wait until all the assets are processed.

**Expected behavior**
All assets are processed without failure.

**Actual behavior**
The SubpassInputComposition.shader job fails processing.

**Screenshot**
![AP_AndroFailed](https://user-images.githubusercontent.com/86953659/162748409-3f6b42ca-e1ff-4a96-9a79-8b04fa10bac8.PNG)

**Found in Branch**
ASV: Stabilization/2205([3efc7e3](https://github.com/o3de/o3de-atom-sampleviewer/commit/3efc7e3ae3d7441257ab3e68ccc457ff6b0f8491))
O3DE: Stabilization/2205([3e47df2](https://github.com/o3de/o3de/commit/3e47df2e0fea9f57d207e6c739938bd1c4019c98))

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i5-9600K
 - GPU: NVIDIA GeForce RTX 2070
 - Memory: 16GB
 
**Additional context**
[SubpassInputComposition.shader-367477699-19997.log](https://github.com/o3de/o3de-atom-sampleviewer/files/8464411/SubpassInputComposition.shader-367477699-19997.log)

**Comment by moudgils** [comment]
Old bug. Check if this is still applicable. Thanks.

**Comment by LB-MateuszSzweda** [comment]
Issue verified as not occuring on Stabilization/2305 (9b1b23c) build. The SubpassInputComposition.shader is processed without errors for windows and android platform.

It seems that our team lack the permission to close the issues in **o3de-atom-sampleviewer** repository directly but the issue can be closed.
