### ISSUE TITLE
Warning is displayed after creating MaterialEditorTest type of material

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de-atom-sampleviewer#415]
**Describe the bug**
After creating the MaterialEditorTest material, "No per-object ShaderResourceGroup found" warning is displayed.

**Steps to reproduce**
1. Launch the Material Editor.
2. Create a new material using the MaterialEditorTest type.

**Expected behavior**
The MaterialEditorTest material is created without issues.

**Actual behavior**
"No per-object ShaderResourceGroup found" warning is displayed upon creation of the material.

**Screenshots/Video**

![Screenshot from 2022-04-12 10-11-27](https://user-images.githubusercontent.com/86952009/162914462-bb428135-f51d-48d6-a27f-3846c01a9557.png)

https://user-images.githubusercontent.com/86952009/162914570-f6033c2f-98d3-4e63-8385-f42be095499c.mp4

**Found in Branch**
Stabilization/2205 [(3e47df2)](https://github.com/o3de/o3de/commit/3e47df2e0fea9f57d207e6c739938bd1c4019c98)

**Desktop/Device**
- Device: PC
- OS: Ubuntu
- Version 20.04
- CPU Intel Core i5-9600k
- GPU Nvidia GeForce RTX 2060
- Memory 16GB

**Comment by moudgils** [comment]
@LB-BartoszDudzinski  Old bug. Please check if this is still applicable. Thanks

**Comment by LB-BartoszDudzinski** [comment]
Hi @moudgils. The issue does not reproduce on the latest development branch as the mentioned MaterialEditorTest material is no longer available for selection.
