### ISSUE TITLE
Settings categories names are blank for multiple materials

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de-atom-sampleviewer#416]
**Describe the bug**
Multiple materials (ReflectionProbeVisualization, ShadowCatcher and HotReloadTest) categories are blank and without any tooltips.

**Steps to reproduce**
1. Launch the Material Editor.
2. Create the ReflectionProbeVisualization material.
3. Look at the Inspector pane.

**Expected behavior**
Each settings category has a proper name and a tooltip.

**Actual behavior**
Settings category names are blank and tooltips are not displayed.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/162942618-93548401-5397-402d-89aa-326c507991bd.mp4

**Found in Branch**
Stabilization/2205 [(3e47df2)](https://github.com/o3de/o3de/commit/3e47df2e0fea9f57d207e6c739938bd1c4019c98)

**Desktop/Device**
- Device: PC
- OS: Ubuntu
- Version 20.04
- CPU Intel Core i5-9600k
- GPU Nvidia GeForce RTX 2060
- Memory 16GB

**Comment by moudgils** [comment]
@LB-BartoszDudzinski  Old bug. Please check if this is still applicable. Thanks.

**Comment by LB-BartoszDudzinski** [comment]
Hi @moudgils. The issue does not reproduce on the latest development branch as the mentioned materials are no longer available for selection. Closing the issue.
