### ISSUE TITLE
ASV: Readback RPI sample crashes ASV executable if the "Readback resource dimensions" width value is set above default value

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de-atom-sampleviewer#430]
[Migrated from JIRA ATOM-17525]
ASV: Readback RPI sample crashes ASV executable if the "Readback resource dimensions" width value is set above default value

----
Found in Build:

O3de:
commit 0db15cfa0be2d86210a91b8aa761ed413aab824f 

ASV:
commit 0db15cfa0be2d86210a91b8aa761ed413aab824f 

Reproducibility:
90% occurred on 9 out of 10 attempts, not sure why it succeeded once, maybe it was a specific height/width ratio?

Prerequisites:
 - Build the above commits and process all assets

Steps to Reproduce:
1. Launch AtomSampleViewerStandalone.exe
2. Go to: Sample > RPI > Readback
3. Turn up the "Readback resource dimensions" width value past 512
4. Press the "Readback" button

Expected Result:
 - ASV remains stable

Actual Result:
 - AtomSampleViewerStandalone.exe crashes

**Comment by NeilGitGud** [comment]
Closing issue, verified as fixed using dev branch:

O3de:
commit e918c78a7fcef4f23b414438a02eeb43265fb816

ASV:
commit 0a57565fe44c8e2437de1f59bde3c1e0fa7d7289
