### ISSUE TITLE
Bug: fulltestsuite fails at multirenderpipeline

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de-atom-sampleviewer#444]
ASV version: commit 0a57565fe44c8e2437de1f59bde3c1e0fa7d7289 (HEAD -> development, upstream/development)
O3DE version: commit e4c890781372480996e8653a8117867b834b730c (upstream/development, development)

Results:
![imageDiff_multirenderpipeline_Start_window2_2267515 0000](https://user-images.githubusercontent.com/66021303/167888660-8b489f26-08ae-495c-b7ff-f825b5148546.png)
![imageDiff_multirenderpipeline_Start_window1_2267515 0000](https://user-images.githubusercontent.com/66021303/167888662-49d89248-c866-4f73-a47d-abbb6da7421a.png)

**Comment by galibzon** [comment]
ASV Report:
![image](https://user-images.githubusercontent.com/66021303/167889019-4db7814e-b0f6-4deb-8f6e-11f71a24744c.png)

**Comment by moudgils** [comment]
Old bug. Closing this as Anton had merged a PR related to it. We can open a new one in future if needed.
