### ISSUE TITLE
ASV Documentation needed for "Readback" sample

### ISSUE THREAD

**Issue by NeilGitGud** [o3de/o3de-atom-sampleviewer#466]
ASV Documentation needed for "Readback" sample. This documentation needs to present on the ASV Wiki within the RPI section, where I already created a section for it: https://github.com/o3de/o3de-atom-sampleviewer/wiki/RPI-Samples

Please see other samples for format (Within the RHI, RPI, and Features samples). In general each wiki documentation should have the following sections:
- Description
- Debug Menu options (description of what each option does if debug menu is present)
- Test Cases that could be performed on the sample
- Any Automation currently supported or planned for the sample
- Platform support

In addition, please include at least one screenshot of the sample to show the expected visual appearance.

You can either add the text and screenshots to the Wiki yourself using the GHI markdown, or post them to this issue in the comments/attachments and I will add them.

**Comment by Bindless-Chicken** [comment]
You can assign it to me ;)

**Comment by Bindless-Chicken** [comment]
Done
