### ISSUE TITLE
ASV full testsuite crashes on Linux

### ISSUE THREAD

**Issue by martinwinter-huawei** [o3de/o3de-atom-sampleviewer#477]
## Description
The full testsuite `scripts/_fulltestsuite_bv.luac` crashes on Linux at the moment in `MSAA_RPI_ExampleComponent` trying to de-reference an iterator in `Scene::RemoveRenderPipeline(AZ::Name const &)`. 

The relevant call stack is:
* ...
* `void MSAA_RPI_ExampleComponent::Activate()`
* `void MSAA_RPI_ExampleComponent::ChangeRenderPipeline()`
* `void Scene::RemoveRenderPipeline(const RenderPipelineId& pipelineId)`
* `T* operator-> () const`

## Environment
 - OS: `Arch Linux`
- Compiler: `Clang 13.0.1`
- `o3de/development` : `02846cf44347cbf4fae0faacc4a2ba74284908ff`
- `o3de-atom-sampleviewer/development` : `8fb8e0a8c1f68d283cca0c07018c2b7fd2596090`

**Comment by martinwinter-huawei** [comment]
Updated today, still unchanged as of:
* `o3de/development` : `31412043ce89a560f13cec877caf4f91c04c5af1`
* `o3de-atom-sampleviewer/development` : `65993cfde607271cad875fbc1c4e4006b8d27eb8`

**Comment by NeilGitGud** [comment]
Appears to be related, or the same issue as: https://github.com/o3de/o3de-atom-sampleviewer/issues/508

**Comment by moudgils** [comment]
@martinwinter-huawei Is this still relevant? I ran full test suite locally with no crashes. Close if not re-proable

**Comment by moudgils** [comment]
It sounds like a gpu crash. We are aware that there is an issue with streaming textures on Vulkan which is been looked at by @VickyAtAZ so that could be related to this issue but wont know without doing a deeper dive. I think it will be good to close this one and open a new one with output log with -rhi-device-validation=enable
