### ISSUE TITLE
[Linux][Ubuntu 22.04] ASV - Mouse disappears when entering the window

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de-atom-sampleviewer#509]
Branch: `stabilization/2210` for both O3DE + ASV. Same bug occurs in `development`.

The mouse pointer disappears when hovering above the ASV window.

GPU: AMD Radeon VII.
CPU: 8-core Intel i7
64GB RAM

**Comment by smurly** [comment]
ubuntu 20.04 ec2 g4dn.2xlarge nvidia.
commit 6634711124b09765b1df5b4db1f0aa66ea001742 origin/stabilization/2210
mouse pointer is functional in AtomSampleViewerStandalone through NiceDCV remote.
I'm able to navigate imgui menus and select multiple samples. I can modify sample control options through imgui interfaces with mouse

**Comment by LB-JakubSkorupka** [comment]
We noticed that this issue still occurs on Stabilization branch (6e9e09c), although it is possible to view the cursor by pressing "~" key. Verified on AtomSampleViewerStandalone.

**Comment by smurly** [comment]
please merge this fix to stabilization/2210
