### ISSUE TITLE
[Windows] AtomSampleViewerStandalone fails to boot with Vulkan RHI

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de-atom-sampleviewer#561]
**Describe the bug**
Attempting to run the AtomSampleViewerStandalone.exe with the Vulkan RHI fails. Acording to [Testing alternative GPUs or RHI backends](https://www.o3de.org/docs/atom-guide/dev-guide/troubleshoot/#testing-alternative-gpus-or-rhi-backends) using the --rhi=vulkan parameter in the terminal should switch the RHI, but this fails.
It should be noted that Vulkan RHI works on Linux.
Attaching terminal logs from booting attempt.

**Steps to reproduce**
1. Clone the o3de-atom-sampleviewer and build the AtomSampleViewerStandalone according to [Setting up Atom Renderer](https://www.o3de.org/docs/atom-guide/setup-atom-projects/#atom-sample-viewer) .
2. Launch the Windows Terminal in the o3de-atom-sampleviewer folder.
3. Run AtomSampleViewerStandalone.exe --rhi=Vulkan.

**Expected behavior**
AtomSampleViewerStandalone is functioning with Vulkan RHI.

**Actual behavior**
AtomSampleViewerStandalone fails to launch.

**Found in Branch**
O3DE: Development (b5d57f7)
ASV:  Development (9db5301)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 11
 - CPU AMD Ryzen 5 5600H
 - GPU NVIDIA GeForce RTX 3070 Laptop GPU
 - Memory 16GB

**Additional context**
[terminal log.txt](https://github.com/o3de/o3de-atom-sampleviewer/files/10237807/terminal.log.txt)

**Comment by moudgils** [comment]
This issue was addressed.

**Comment by LB-TomaszSerwanski** [comment]
Confirming the issue has been closed as per above comment. It does not reproduce on GameLauncher. Will re-verify on the Standalone once #616 is merged.
