### ISSUE TITLE
AtomSampleViewer ShadowedSponza screen compare tests fail

### ISSUE THREAD

**Issue by smurly** [o3de/o3de-atom-sampleviewer#583]
ASV commit 9f4adc46178bb9a85c85e7b68c5c1dd7ea65a3bc
O3DE commit d2004b0e82b0f41d05de7f1a5bf5a12aa1cab0dd

Repro:
1. build and run AtomSampleViewerStandalone.exe one windows
2. Automation > run script. select scripts/_fulltestsuite_.bv.luac and click Run

Expected result:
tests pass

Actual result:
several screen compares for shadowedsponza fail image comparison

Windows 10
Nvidia RTX 3070 Ti
Driver Version: 30.0.14.9613
Processor: AMD Ryzen Threadripper 3970X 32-Core Processor  (64 CPUs), ~3.7GHz
Memory: 64GB

![image](https://user-images.githubusercontent.com/26234397/217436927-38416204-6596-42b9-a077-9846a8d8ce80.png)
![imageDiff_shadowedsponzatest_directional_nofilter_1675726208 0000](https://user-images.githubusercontent.com/26234397/217436964-3561d35d-cb63-4a6c-990f-4ed8647b5b7d.png)

![image](https://user-images.githubusercontent.com/26234397/217437032-c1282b8b-7f55-4624-ad98-f2229a244b23.png)
![imageDiff_shadowedsponzatest_directional_filter_1675726208 0000](https://user-images.githubusercontent.com/26234397/217437120-b35262b8-4059-49b5-8611-f387cca1d021.png)

**Comment by moudgils** [comment]
Ran locally and this issue was not repro-able. Closing for now. We can open a new one if needed.
