### ISSUE TITLE
AtomSampleViewer is missing test jobs in its new AR location.

### ISSUE THREAD

**Issue by jromnoa** [o3de/o3de-atom-sampleviewer#590]
**Describe the bug**
The new location for ASV AR lacks test jobs to run the tests from https://github.com/o3de/o3de-atom-sampleviewer/tree/development/Standalone/PythonTests 

**Assets required**
N/A

**Steps to reproduce**
1. Navigate to the new ASV AR page: [Had to delete URL, message me for location] 
2. Once on the page, try to find a job that runs the tests from https://github.com/o3de/o3de-atom-sampleviewer/tree/development/Standalone/PythonTests  
3. **Result:** There is no job that runs these tests. There used to be a `test_profile` job that would run these tests.

**Expected behavior**
AtomSampleViewer AR can build and run tests.

**Actual behavior**
AtomSampleViewer AR can build, but it doesn't run the tests any more.

**Screenshots/Video**
N/A

**Found in Branch**
development

**Commit ID from [o3de/o3de-atom-sampleviewer](https://github.com/o3de/o3de-atom-sampleviewer/) Repository**
b818bafb6bc0b2f21ef8bd5ef193459566c944df but the issue started occurring in 046a2df91ca691656c7029359f2f239156550675

**Desktop/Device (please complete the following information):**
Whatever AR machines specs are for these jobs (not sure at this time).

**Additional Info:** 
This breaks an Atom metrics job that we use to help monitor performance and we'd like to have the tests restored. The tests also help us get a source of truth separate from our local machines (by using the AR run as a source of truth).

**Comment by shirangj** [comment]
This should be resolved by https://github.com/o3de/o3de-atom-sampleviewer/pull/591
