### ISSUE TITLE
AtomSampleViewerStandalone cannot be built

### ISSUE THREAD

**Issue by LB-HubertUberman** [o3de/o3de-atom-sampleviewer#600]
**Describe the bug**
During ASV setup it is not possible to build AtomSampleViewerStandalone as the user is given an error stating that it is an "unknown target" on a Linux machine or "Project file does not exist" on a Windows machine. Please note that also after launching the project's solution via Visual Studio the AtomSampleViewerStandalone target is not present anywhere and therefore cannot be built. Also after building the project using Project Manager the process completes without any issues but AtomSampleViewerStandalone is not present in the project folder. The issue occurs on both Windows and Linux.

This issue should be considered as a Critical.

**Steps to reproduce**
1. Clone the project using the following commands:
`git clone https://github.com/o3de/o3de-atom-sampleviewer.git`
2. Navigate to the o3de-atom-sampleviewer folder and build the project using the following commands:
`cmake -B build/windows -S . -G "Visual Studio 16"`
`cmake --build build/windows --target Editor AtomSampleViewerStandalone --config profile -- -m`

**Expected behavior**
The user is able to build AtomSampleViewerStandalone.

**Actual behavior**
AtomSampleViewerStandalone cannot be built.

**Screenshots**

Linux error:
![ASV_Linux_Error](https://user-images.githubusercontent.com/96232062/228538115-59789df1-d9c2-4373-b184-d5c0e54d75be.png)

Windows error:
![ASV_Windows_Error](https://user-images.githubusercontent.com/96232062/228538102-1c0bf4e1-6d32-420b-b485-4c1e460e2edd.png)

Visual Studio solution:
![ASV_VS_Solution](https://user-images.githubusercontent.com/96232062/228534474-18960dc3-4b6e-4afb-adce-e7b9612975dc.png)

**Found in Branch**
Stabilization/2305
Development 

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
o3de-atom-sampleviewer: Development (https://github.com/o3de/o3de-atom-sampleviewer/commit/873499a3772d2ede280bb28afb8d6b7301a739c9)
O3DE: Development (https://github.com/o3de/o3de/commit/9f4341ff5f5eb0ad4ddf997469488ba8642cc762)
o3de-atom-sampleviewer: Stabilization/2305(https://github.com/o3de/o3de-atom-sampleviewer/commit/cee84fa2a7e85b08128271afef3c36b06284d8d7)
O3DE: Stabilization/2305 Installer build (https://o3debinaries.org/stabilization-2305/Latest/Linux/O3DE_latest.deb)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by lmbr-pip** [comment]
It does seem like there is no `AtomStampleViewerStandalone` target any more. But it is still in the CMake file in dev https://github.com/o3de/o3de-atom-sampleviewer/blob/development/Standalone/CMakeLists.txt#L16

**Comment by galibzon** [comment]
It seems AtomSampleViewerStandalone target was inadvertently removed  in this PR: https://github.com/o3de/o3de-atom-sampleviewer/pull/599. Users should use AtomSampleViewer.GameLauncher target as workaround.

**Comment by LB-KacperKapusta** [comment]
I have encountered an issue on the latest Stabilization/2305 Installer on Ubuntu 20.04 where running the AtomSampleViewer.GameLauncher, as suggested in the comment above, does not load the ASV or its toolbar. The GameLauncher window is completely empty and no level can be loaded via the ImGui. All assets have been processed without failures. The issue can be reproduced only on one machine:
- Ubuntu 20.04.6 LTS
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
![Ubuntu_2004_issue](https://user-images.githubusercontent.com/86953659/228803362-73a8b8fc-c6de-4f6f-ad13-084f4fc67745.png)
Please note that on another machine with the same CPU/GPU but using Ubuntu 22.04 instead the issue does not occur:
![Ubuntu_2204_noissue](https://user-images.githubusercontent.com/86953659/228804277-97facd41-c932-4750-8f59-10fad9e8b79e.png)
However, on yet another Ubuntu 20.04 machine the issue also does not reproduce:
- CPU: Intel Core i7-8700K
- GPU: NVIDIA GeForce RTX 2080 Ti

Please note that on each machine we used exact same steps to setup the AtomSampleViewer. Different NVIDIA Drivers were verified (including the ones used by the machines not affected by the issue) but without any effect. 
Should this be logged as a separate issue?

Additional info:
[Game_affectedmachine.log](https://github.com/o3de/o3de-atom-sampleviewer/files/11110383/Game_affectedmachine.log)

**Comment by moudgils** [comment]
@AMZN-alexpete Is there any plan to bring ASVStandalone back?

**Comment by AMZN-alexpete** [comment]
Oh yeah, that target shouldn't have been removed, let me add that back

**Comment by AMZN-alexpete** [comment]
This PR https://github.com/o3de/o3de-atom-sampleviewer/pull/616 adds the standalone target back.
