### ISSUE TITLE
ASV Transparency Sample fails

### ISSUE THREAD

**Issue by amzn-tommy** [o3de/o3de-atom-sampleviewer#608]
Run the transparent test script in ASV

![Capture](https://user-images.githubusercontent.com/82672795/229185024-3f8db95d-c9a4-4aba-a4e4-8fa25c1f1c63.PNG)

development branch
commit b3ef3a9956581456a07c83985445707ecb7d2180

both DX12 and Vulkan

**Comment by moudgils** [comment]
https://github.com/o3de/o3de/pull/15613
